### ISSUE TITLE
It does not work on my project

### ISSUE THREAD

**Issue by qyhdt** [rllola/electron-example#19]
Hey there, for I've been workiong on my electron application autoupdate for weeks, I also checked all repositories related update electron application, but none of them worked, so i saw your project is simple to learn , can you tell me how can I get my application autoupdate worked
see my update service folder
![image](https://user-images.githubusercontent.com/7843730/114507169-54025100-9c65-11eb-9f83-549b66370472.png)

**Comment by qyhdt** [comment]
error says:
![Uploading image.png…]()

**Comment by qyhdt** [comment]
error says:
![image](https://user-images.githubusercontent.com/7843730/114507327-8e6bee00-9c65-11eb-8524-080c0c47870a.png)

**Comment by rllola** [comment]
Hi @qyhdt,

So Setup executables (your .exe file) are if I am not mistaken installer for windows. We are looking for .nupkg file for updates tho (see our latest release : https://github.com/rllola/electron-example/releases/tag/v0.0.45).

If you want to create one you will need to add the `maker-squirrel` plugin. See the [doc](https://www.electronforge.io/config/makers/squirrel.windows) in electron-forge website.

You have an example here:
https://github.com/rllola/electron-example/blob/master/forge.config.js#L21-L27

You will probably not need a certificate at this point but at the end you might want one. You can generate a dummy by following this blog post : https://www.update.rocks/blog/create-a-self-signed-certificate/

**Comment by rllola** [comment]
I see on your repo you are actually using `electron-builder`.

You might want to add as a target `squirrel` and you will probably need to install `npm i --save-dev electron-builder-squirrel-windows`.

Let me know if this works. You should have a `RELEASES` file and a `.nupkg` file generated.

You can also test our service : https://www.update.rocks/
And once you get it to work you can transfer to your own update server. It is free for open source project and I can guide you throught it.

**Comment by qyhdt** [comment]
Thanks so much, I will try it now.

**Comment by qyhdt** [comment]
@rllola I've tried your solution, but it still does not work, even did not call updater.init() see below code snippet
![image](https://user-images.githubusercontent.com/7843730/114685839-cbf37880-9d44-11eb-888d-751f9694c1a4.png)

**Comment by qyhdt** [comment]
I built a local service for update:
![image](https://user-images.githubusercontent.com/7843730/114686026-fa715380-9d44-11eb-8509-5c337b0fd84f.png)

Repo: https://github.com/qyhdt/campaign-dev-helper
Could you try it in your local environment (windows), but I think it is not related whatever your OS is.

**Comment by rllola** [comment]
Nope sorry I cant.

And I already told you, you need .nupkg and RELEASES files. People before you successfully did it. I am sure you can manage. Closing the issue.
